//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.32559
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Illallangi.CloudStoragePS")]
[assembly: AssemblyCompany("Illallangi Enterprises")]
[assembly: AssemblyProduct("Cloud Storage PowerShell Module")]
[assembly: AssemblyCopyright("Copyright © Illallangi Enterprises 2013")]
[assembly: ComVisible(false)]
[assembly: AssemblyInformationalVersion("Debug Build")]
[assembly: Guid("e92417b8-61ad-48e5-869d-80a19f6f9d93")]
[assembly: AssemblyVersion("0.0.0.1")]
[assembly: AssemblyFileVersion("0.0.0.1")]


